language: php
dist: xenial

# Since Xenial services are not started by default, we need to instruct it below to start.
services:
  - xvfb
  - mysql
  - docker

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# Test main supported versions of PHP against latest WP.
php:
  - 7.4

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
   fast_finish: true
   include:
   - name: "Coding standard check"
   php: 7.4
   env: WP_VERSION=latest WP_MULTISITE=0 RUN_PHPCS=1

   before_script:
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - composer install --no-dev

script:
- bash tests/bin/phpcs.sh