language: php
dist: xenial

# Since Xenial services are not started by default, we need to instruct it below to start.
services:
  - xvfb
  - mysql
  - docker

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

# Test main supported versions of PHP against latest WP.
php:
  - 7.4

env:
  - WP_VERSION=latest WP_MULTISITE=0 RUN_PHPCS=1 WC_VERSION=4.0.0
  - WP_VERSION=latest WP_MULTISITE=0 RUN_PHPCS=0 WC_VERSION=4.0.0

before_script:
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - composer install
    - bash tests/bin/install-wp-tests.sh test-travis root '' localhost $WP_VERSION
    - bash tests/bin/travis.sh

script:
- bash tests/bin/phpcs.sh
- bash tests/bin/phpunit.sh

branches:
  only:
    - master