name: CI Test
on:
  push:
    branches:
      - develop-github-actions
      - master

jobs:
  WC:
    name: Latest WP
    strategy:
      matrix:
        wordpress: [latest]
        woocommerce: [4.3.2, 4.3.1, 4.3.0, 4.2.2, 4.2.1, 4.2.0, 4.1.0, 3.9.0, 3.8.0, 3.7.0]
    runs-on: ubuntu-latest
    container:
      image: chriszarate/wordpress-phpunit:6.0.6
      volumes:
        - "testsuite:/tmp"
    services:
      mysql:
        image: mariadb:10.2.33
        env:
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wp_user
          MYSQL_PASSWORD: wp_pass
          MYSQL_ROOT_PASSWORD: "root"
          options: --health-cmd="mysqladmin ping" --health-interval=40s --health-timeout=30s --health-retries=3
    steps:
      - name: Settup repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Settup WooCommerce
        uses: actions/checkout@v2
        with:
          repository: woocommerce/woocommerce
          ref: ${{ matrix.woocommerce }}
          path: woocommerce
      - name: Install WP Testsuite
        run: |
          chmod +x ./main/tests/bin/install-wp-tests.sh
          ./main/tests/bin/install-wp-tests.sh wordpress_test wp_user wp_pass mysql ${{ matrix.wordpress }} true
      - name: Run PHPUnit
        run: |
          phpunit -c main/phpunit.xml