name: CI Build
on: [push]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        php: [7.3]
        wordpress: [5.2.2]
        woocommerce: [4.1.0]
        phpunit: [7.5.15]
        wpcs: [2.1.1]
    runs-on: ubuntu-latest
    container:
      image: chriszarate/wordpress-phpunit:6.0.6
      volumes:
        - ".:/app"
        - "testsuite:/tmp"
    services:
      mysql:
        image: mariadb:10.2
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: "wordpress_test"
          MYSQL_ROOT_PASSWORD: "password"
        volumes:
        - mysql:/var/lib/mysql
    steps:
    - name: Testing
      run: |
        ls
