name: CI Test
on: [push]

jobs:
  build:
    name: PHPUnit
    strategy:
      matrix:
        php: [7.3]
        wordpress: [5.2.2]
        woocommerce: [4.1.0]
        phpunit: [7.5.15]
        wpcs: [2.1.1]
    runs-on: ubuntu-latest
    container:
      image: chriszarate/wordpress-phpunit:6.0.6
      volumes:
        - "testsuite:/tmp"
    services:
      mysql:
        image: mariadb:10.2
        env:
          MYSQL_DATABASE: "wordpress_test"
          MYSQL_ROOT_PASSWORD: "password"
    steps:
    - name: Settup repo
      uses: actions/checkout@v2
      with:
        path: main
    - name: Settup WooCommerce
      uses: actions/checkout@v2
      with:
        repository: woocommerce/woocommerce
        path: woocommerce
    - name: Testing
      run: |
        ls -la
